plugins:
  - jekyll-seo-tag

markdown: kramdown
remote_theme: borgr/just-the-docs
aux_links:
  "Model Recycling on GitHub":
    - "//github.com/IBM/model-recycling"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
url: "https://ibm.github.io"

# Footer - "Back to top" link
back_to_top: true
back_to_top_text: "Back to top"

logo: "/recybert.png"
color_scheme: "recybert"
title: "Model Recycling"
tagline: "Just pick which model to finetune"
author:
  name: Leshem Choshen
  twitter: LChoshen
  image: "/Twitter_card.png"
twitter:
  username: LChoshen
  card: summary_large_image
defaults:
  - scope:
      path: ""
    values:
      image: "/Twitter_card.png"
