plugins:
- jekyll-seo-tag

markdown: kramdown
remote_theme: borgr/just-the-docs
aux_links:
  "Model Recycling on GitHub":
    - "//github.com/IBM/model-recycling"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
url: "https://ibm.github.io/model-recycling/"

# Footer - "Back to top" link
back_to_top: true
back_to_top_text: "Back to top"

logo: "/recybert.png"
color_scheme: "recybert"

tagline: "Just pick which model to finetune"
title: "Model-recycling - the best model per architecture"
description: Hardly anyone trains from scratch anymore, we all finetune over a pretrained model. Some finetuned models are better base models than the pretrained models themselves. This site presents a dynamic view of the best models to choose for a given model size and architecture.
image: "https://raw.githubusercontent.com/IBM/model-recycling/master/Twitter_card.png"
author: LChoshen
twitter:
  username: LChoshen
  card: summary_large_image
